server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /var/lib/promtail/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: mikrotik-syslog
    syslog:
      listen_address: 0.0.0.0:${PROMTAIL_SYSLOG_PORT:-1514}
      label_structured_data: true
      labels:
        job: mikrotik-syslog
        app: mikrotik
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: router
      - source_labels: ['__syslog_message_severity']
        target_label: severity
      - source_labels: ['__syslog_message_app_name']
        target_label: routeros_app
