global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 25s
rule_files:
  - /etc/prometheus/alerts/*.yml
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
scrape_configs:
  - job_name: routeros-exporter
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/targets-mikrotik.json
    relabel_configs:
      - source_labels: [router]
        target_label: instance

  - job_name: snmp-exporter
    scrape_interval: 60s
    metrics_path: /snmp
    params:
      module: [mikrotik]
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/snmp-targets.json
    relabel_configs:
      - source_labels: [snmp_target]
        target_label: __param_target
      - source_labels: [snmp_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: ['loki:3100']

  - job_name: promtail
    static_configs:
      - targets: ['promtail:9080']
